projet/src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer')]
    private $_id;

    #[ORM\Column(type: 'string', length: 255)]
    //#[Assert\NotBlank()]
    //#[Assert\Lenght(min: 2, max: 50)]
    private $_prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $_nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $_telephone;

    #[ORM\Column(type: 'string', length: 255)]
    private $_email;

    #[ORM\Column(type: 'string', length: 255)]
    private $_adresse;

    #[ORM\Column(type: 'string', length: 255)]
    private $_poste;

    #[ORM\Column(type: 'string', length: 255)]
    private $_salaire;

    #[ORM\Column(type: 'string', length: 255)]
    private $_datedenaissance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $_id): self
    {
        $this->_id = $_id;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->_prenom;
    }

    public function setPrenom(string $_prenom): self
    {
        $this->_prenom = $_prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->_nom;
    }

    public function setNom(string $_nom): self
    {
        $this->_nom = $_nom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->_telephone;
    }

    public function setTelephone(string $_telephone): self
    {
        $this->_telephone = $_telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->_email;
    }

    public function setEmail(string $_email): self
    {
        $this->_email = $_email;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->_adresse;
    }

    public function setAdresse(string $_adresse): self
    {
        $this->_adresse = $_adresse;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->_poste;
    }

    public function setPoste(string $_poste): self
    {
        $this->_poste = $_poste;

        return $this;
    }

    public function getSalaire(): ?string
    {
        return $this->_salaire;
    }

    public function setSalaire(string $_salaire): self
    {
        $this->_salaire = $_salaire;

        return $this;
    }

    public function getDatedenaissance(): ?string
    {
        return $this->_datedenaissance;
    }

    public function setDatedenaissance(string $_datedenaissance): self
    {
        $this->_datedenaissance = $_datedenaissance;

        return $this;
    }
}

projet/templates/pages/entreprise/edit.html.twig
{% extends "base.html.twig" %}

{% block body %}
 <div class="container">
   <h1 class="mt-4">Modification d'une ligne</h1>

    <a href="{{ path('annuaire') }}" class="btn btn-info">
      Revenir vers l'annuaire
    </a>

{{ form_start(form) }}

<div class="form-group">
 {{ form_label(form.nom) }}
 {{ form_widget(form.nom) }}
 <div class="form-error">
   {{ form_errors(form.nom) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.prenom) }}
 {{ form_widget(form.prenom) }}
 <div class="form-error">
   {{ form_errors(form.prenom) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.telephone) }}
 {{ form_widget(form.telephone) }}
 <div class="form-error">
   {{ form_errors(form.telephone) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.email) }}
 {{ form_widget(form.email) }}
 <div class="form-error">
   {{ form_errors(form.email) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.adresse) }}
 {{ form_widget(form.adresse) }}
 <div class="form-error">
   {{ form_errors(form.adresse) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.poste) }}
 {{ form_widget(form.poste) }}
 <div class="form-error">
   {{ form_errors(form.poste) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.salaire) }}
 {{ form_widget(form.salaire) }}
 <div class="form-error">
   {{ form_errors(form.salaire) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.datedenaissance) }}
 {{ form_widget(form.datedenaissance) }}
 <div class="form-error">
   {{ form_errors(form.datedenaissance) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.submit2) }}
 {{ form_widget(form.submit2) }}
</div>

 {{ form_end(form) }}
 </div>

{% endblock %}

projet/templates/pages/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annuaire Entreprise{% endblock %}
{% block body %}
  <div class="container mt-4">
    <h1>Annuaire</h1>

    <a href="{{ path('enteprise_new') }}" class="btn btn-info">
      Créer une nouvelle ligne
    </a>
     {% for message in app.flashes('success') %}
   <div class="alert alert-success">
     {{ message}}
   </div>
   {% endfor %}

    <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Numéro</th>
      <th scope="col">Nom</th>
      <th scope="col">Prenom</th>
      <th scope="col">Téléphone</th>
      <th scope="col">Email</th>
      <th scope="col">Adresse</th>
      <th scope="col">Poste</th>
      <th scope="col">Salaire</th>
      <th scope="col">Date de Naissance</th>
      <th scope="col">Modifier</th>
      <th scope="col">Supprimer</th>
    </tr>
  </thead>
  <tbody>
    {% for annuaire in annuaire %}
    <tr class="table-info">
      <th scope="row">{{ annuaire.id }}</th>
      <td>{{ annuaire.nom }}</td>
      <td>{{ annuaire.prenom }}</td>
      <td>{{ annuaire.telephone }}</td>
      <td>{{ annuaire.email }}</td>
      <td>{{ annuaire.adresse }}</td>
      <td>{{ annuaire.poste }}</td>
      <td>{{ annuaire.salaire }}</td>
      <td>{{ annuaire.datedenaissance }}</td>
      <td><a href="{{ path('entreprise.edit', {id: annuaire.id}) }}" class="img-fluid"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABmJLR0QA/wD/AP+gvaeTAAAAhElEQVRIie2TwQnAIAxF35Klh3YBdxDqPh3HQdq7gj00ooi3xkvxQ0BzeD8JfJh6ZYEbWEfAHZCkIrCPgAfgrN4qm9STG+llk0sTngAvJkH+VgMeBOobM6cFz3c22vAIbNJbKGc5JnzCfwCHEpgcorWCfwpRawDKk7cGdanBewaq8KmuHlYrZbGe+TNUAAAAAElFTkSuQmCC"/></a></td>
      <td><a href="{{ path('entreprise.delete', {id: annuaire.id}) }}" class="img-fluid"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAABmJLR0QA/wD/AP+gvaeTAAAAtElEQVRIie2VQQ6CQAxFX8R7uPM4xsPgCTmFSzW6niUGBTezMnawLTIQecks+1+bzgD8G4Wjdg9sgeNAvXzNHah/Fb6L4Z3y1LFWTWWQSaf6JFhZulLSjeCYOQH/foMUntrx2d87p1xiMWOS4ssAYjFjkhNnE4s3UoEpowAa7G+4AdZSeGriJ3CzdBy5Ag+LGHx7TtYu4nc8H5FkbbaJ+9gALfqn1MZaFwd0/+YAlF7pwvx5Abo6e/T2cOSLAAAAAElFTkSuQmCC"/></a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
  </div>
{% endblock %}

projet/templates/pages/entreprise/new.html.twig
{% extends "base.html.twig" %}

{% block body %}
 <div class="container">
   <h1 class="mt-4">Création d'une nouvelle ligne</h1>

    {% for message in app.flashes('success') %}
   <div class="alert alert-success mt-4">
     {{ message}}
   </div>
   {% endfor %}

    <a href="{{ path('annuaire') }}" class="btn btn-info">
      Revenir vers l'annuaire
    </a>

{{ form_start(form) }}

<div class="form-group">
 {{ form_label(form.nom) }}
 {{ form_widget(form.nom) }}
 <div class="form-error">
   {{ form_errors(form.nom) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.prenom) }}
 {{ form_widget(form.prenom) }}
 <div class="form-error">
   {{ form_errors(form.prenom) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.telephone) }}
 {{ form_widget(form.telephone) }}
 <div class="form-error">
   {{ form_errors(form.telephone) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.email) }}
 {{ form_widget(form.email) }}
 <div class="form-error">
   {{ form_errors(form.email) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.adresse) }}
 {{ form_widget(form.adresse) }}
 <div class="form-error">
   {{ form_errors(form.adresse) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.poste) }}
 {{ form_widget(form.poste) }}
 <div class="form-error">
   {{ form_errors(form.poste) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.salaire) }}
 {{ form_widget(form.salaire) }}
 <div class="form-error">
   {{ form_errors(form.salaire) }}
 </div>
</div>

<div class="form-group">
 {{ form_label(form.datedenaissance) }}
 {{ form_widget(form.datedenaissance) }}
 <div class="form-error">
   {{ form_errors(form.datedenaissance) }}
 </div>

 </div>
 {{ form_end(form) }}
 </div>


{% endblock %}